package com.eyeball.randomutils.coremod;

import com.google.common.collect.Lists;
import org.objectweb.asm.*;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.MethodNode;

public class Transformer implements Opcodes {

    public static byte[] transformEnderPearl(byte[] classBytes) {
        ClassNode classNode = new ClassNode();
        ClassReader classReader = new ClassReader(classBytes);
        classReader.accept(classNode, 0);

        for (MethodNode methodNode : Lists.newArrayList(classNode.methods)) {
            if (methodNode.name.equals("onItemRightClick") && methodNode.desc.equals("(Lnet/minecraft/item/ItemStack;Lnet/minecraft/world/World;Lnet/minecraft/entity/player/EntityPlayer;)Lnet/minecraft/item/ItemStack;")) {
                methodNode.name = "old_onItemRightClick";
            }
        }

        MethodVisitor methodVisitor = classNode.visitMethod(ACC_PUBLIC, "onItemRightClick", "(Lnet/minecraft/item/ItemStack;Lnet/minecraft/world/World;Lnet/minecraft/entity/player/EntityPlayer;)Lnet/minecraft/item/ItemStack;", null, null);
        methodVisitor.visitCode();
        Label l0 = new Label();
        methodVisitor.visitLabel(l0);
        methodVisitor.visitLineNumber(13, l0);
        methodVisitor.visitVarInsn(ALOAD, 3);
        methodVisitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/EntityPlayer", "capabilities", "Lnet/minecraft/entity/player/PlayerCapabilities;");
        methodVisitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/PlayerCapabilities", "isCreativeMode", "Z");
        Label l1 = new Label();
        methodVisitor.visitJumpInsn(IFNE, l1);
        Label l2 = new Label();
        methodVisitor.visitLabel(l2);
        methodVisitor.visitLineNumber(14, l2);
        methodVisitor.visitVarInsn(ALOAD, 1);
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitFieldInsn(GETFIELD, "net/minecraft/item/ItemStack", "stackSize", "I");
        methodVisitor.visitInsn(ICONST_1);
        methodVisitor.visitInsn(ISUB);
        methodVisitor.visitFieldInsn(PUTFIELD, "net/minecraft/item/ItemStack", "stackSize", "I");
        methodVisitor.visitLabel(l1);
        methodVisitor.visitLineNumber(15, l1);
        methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
        methodVisitor.visitVarInsn(ALOAD, 2);
        methodVisitor.visitVarInsn(ALOAD, 3);
        methodVisitor.visitLdcInsn("random.bow");
        methodVisitor.visitLdcInsn(0.5f);
        methodVisitor.visitLdcInsn(0.4f);
        methodVisitor.visitFieldInsn(GETSTATIC, "net/minecraft/item/ItemEnderPearl", "itemRand", "Ljava/util/Random;");
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextFloat", "()F", false);
        methodVisitor.visitLdcInsn(0.4f);
        methodVisitor.visitInsn(FMUL);
        methodVisitor.visitLdcInsn(0.8f);
        methodVisitor.visitInsn(FADD);
        methodVisitor.visitInsn(FDIV);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/world/World", "playSoundAtEntity", "(Lnet/minecraft/entity/Entity;Ljava/lang/String;FF)V", false);
        Label l3 = new Label();
        methodVisitor.visitLabel(l3);
        methodVisitor.visitLineNumber(17, l3);
        methodVisitor.visitVarInsn(ALOAD, 2);
        methodVisitor.visitFieldInsn(GETFIELD, "net/minecraft/world/World", "isRemote", "Z");
        Label l4 = new Label();
        methodVisitor.visitJumpInsn(IFNE, l4);
        Label l5 = new Label();
        methodVisitor.visitLabel(l5);
        methodVisitor.visitLineNumber(18, l5);
        methodVisitor.visitVarInsn(ALOAD, 2);
        methodVisitor.visitTypeInsn(NEW, "net/minecraft/entity/item/EntityEnderPearl");
        methodVisitor.visitInsn(DUP);
        methodVisitor.visitVarInsn(ALOAD, 2);
        methodVisitor.visitVarInsn(ALOAD, 3);
        methodVisitor.visitMethodInsn(INVOKESPECIAL, "net/minecraft/entity/item/EntityEnderPearl", "<init>", "(Lnet/minecraft/world/World;Lnet/minecraft/entity/EntityLivingBase;)V", false);
        methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/world/World", "spawnEntityInWorld", "(Lnet/minecraft/entity/Entity;)Z", false);
        methodVisitor.visitInsn(POP);
        methodVisitor.visitLabel(l4);
        methodVisitor.visitLineNumber(21, l4);
        methodVisitor.visitFrame(F_SAME, 0, null, 0, null);
        methodVisitor.visitVarInsn(ALOAD, 1);
        methodVisitor.visitInsn(ARETURN);
        Label l6 = new Label();
        methodVisitor.visitLabel(l6);
        methodVisitor.visitLocalVariable("this", "Lnet/minecraft/item/ItemEnderPearl;", null, l0, l6, 0);
        methodVisitor.visitLocalVariable("p_77659_1_", "Lnet/minecraft/item/ItemStack;", null, l0, l6, 1);
        methodVisitor.visitLocalVariable("p_77659_2_", "Lnet/minecraft/world/World;", null, l0, l6, 2);
        methodVisitor.visitLocalVariable("p_77659_3_", "Lnet/minecraft/entity/player/EntityPlayer;", null, l0, l6, 3);
        methodVisitor.visitMaxs(7, 4);
        methodVisitor.visitEnd();
        classNode.visitEnd();

        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);
        classNode.accept(writer);
        return writer.toByteArray();
    }

    public static byte[] transformEnderPearlEntity(byte[] classBytes, float damageAmount) {
        ClassNode classNode = new ClassNode();
        ClassReader classReader = new ClassReader(classBytes);
        classReader.accept(classNode, 0);

        for (MethodNode methodNode : Lists.newArrayList(classNode.methods)) {
            if (methodNode.name.equals("onImpact") && methodNode.desc.equals("(Lnet/minecraft/util/MovingObjectPosition;)V")) {
                methodNode.name = "old_onImpact";
            }
        }

        MethodVisitor visitor = classNode.visitMethod(ACC_PROTECTED, "onImpact", "(Lnet/minecraft/util/MovingObjectPosition;)V", null, null);
        visitor.visitCode();
        Label l0 = new Label();
        visitor.visitLabel(l0);
        visitor.visitLineNumber(19, l0);
        visitor.visitVarInsn(ALOAD, 1);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/util/MovingObjectPosition", "entityHit", "Lnet/minecraft/entity/Entity;");
        Label l1 = new Label();
        visitor.visitJumpInsn(IFNULL, l1);
        Label l2 = new Label();
        visitor.visitLabel(l2);
        visitor.visitLineNumber(20, l2);
        visitor.visitVarInsn(ALOAD, 1);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/util/MovingObjectPosition", "entityHit", "Lnet/minecraft/entity/Entity;");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitMethodInsn(INVOKESTATIC, "net/minecraft/util/DamageSource", "causeThrownDamage", "(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/Entity;)Lnet/minecraft/util/DamageSource;", false);
        visitor.visitInsn(FCONST_0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/Entity", "attackEntityFrom", "(Lnet/minecraft/util/DamageSource;F)Z", false);
        visitor.visitInsn(POP);
        visitor.visitLabel(l1);
        visitor.visitLineNumber(23, l1);
        visitor.visitFrame(F_SAME, 0, null, 0, null);
        visitor.visitInsn(ICONST_0);
        visitor.visitVarInsn(ISTORE, 2);
        Label l3 = new Label();
        visitor.visitLabel(l3);
        visitor.visitFrame(F_APPEND, 1, new Object[]{INTEGER}, 0, null);
        visitor.visitVarInsn(ILOAD, 2);
        visitor.visitIntInsn(BIPUSH, 32);
        Label l4 = new Label();
        visitor.visitJumpInsn(IF_ICMPGE, l4);
        Label l5 = new Label();
        visitor.visitLabel(l5);
        visitor.visitLineNumber(24, l5);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "worldObj", "Lnet/minecraft/world/World;");
        visitor.visitLdcInsn("portal");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "posX", "D");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "posY", "D");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "rand", "Ljava/util/Random;");
        visitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextDouble", "()D", false);
        visitor.visitLdcInsn(new Double("2.0"));
        visitor.visitInsn(DMUL);
        visitor.visitInsn(DADD);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "posZ", "D");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "rand", "Ljava/util/Random;");
        visitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextGaussian", "()D", false);
        visitor.visitInsn(DCONST_0);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "rand", "Ljava/util/Random;");
        visitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Random", "nextGaussian", "()D", false);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/world/World", "spawnParticle", "(Ljava/lang/String;DDDDDD)V", false);
        Label l6 = new Label();
        visitor.visitLabel(l6);
        visitor.visitLineNumber(23, l6);
        visitor.visitIincInsn(2, 1);
        visitor.visitJumpInsn(GOTO, l3);
        visitor.visitLabel(l4);
        visitor.visitLineNumber(27, l4);
        visitor.visitFrame(F_CHOP, 1, null, 0, null);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "worldObj", "Lnet/minecraft/world/World;");
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/world/World", "isRemote", "Z");
        Label l7 = new Label();
        visitor.visitJumpInsn(IFNE, l7);
        Label l8 = new Label();
        visitor.visitLabel(l8);
        visitor.visitLineNumber(28, l8);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        Label l9 = new Label();
        visitor.visitJumpInsn(IFNULL, l9);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitTypeInsn(INSTANCEOF, "net/minecraft/entity/player/EntityPlayerMP");
        visitor.visitJumpInsn(IFEQ, l9);
        Label l10 = new Label();
        visitor.visitLabel(l10);
        visitor.visitLineNumber(29, l10);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitTypeInsn(CHECKCAST, "net/minecraft/entity/player/EntityPlayerMP");
        visitor.visitVarInsn(ASTORE, 2);
        Label l11 = new Label();
        visitor.visitLabel(l11);
        visitor.visitLineNumber(31, l11);
        visitor.visitVarInsn(ALOAD, 2);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/EntityPlayerMP", "playerNetServerHandler", "Lnet/minecraft/network/NetHandlerPlayServer;");
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/network/NetHandlerPlayServer", "func_147362_b", "()Lnet/minecraft/network/NetworkManager;", false);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/network/NetworkManager", "isChannelOpen", "()Z", false);
        visitor.visitJumpInsn(IFEQ, l9);
        visitor.visitVarInsn(ALOAD, 2);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/EntityPlayerMP", "worldObj", "Lnet/minecraft/world/World;");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "worldObj", "Lnet/minecraft/world/World;");
        visitor.visitJumpInsn(IF_ACMPNE, l9);
        Label l12 = new Label();
        visitor.visitLabel(l12);
        visitor.visitLineNumber(32, l12);
        visitor.visitTypeInsn(NEW, "net/minecraftforge/event/entity/living/EnderTeleportEvent");
        visitor.visitInsn(DUP);
        visitor.visitVarInsn(ALOAD, 2);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "posX", "D");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "posY", "D");
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitFieldInsn(GETFIELD, "net/minecraft/entity/item/EntityEnderPearl", "posZ", "D");
        visitor.visitLdcInsn(new Float("5.0"));
        visitor.visitMethodInsn(INVOKESPECIAL, "net/minecraftforge/event/entity/living/EnderTeleportEvent", "<init>", "(Lnet/minecraft/entity/EntityLivingBase;DDDF)V", false);
        visitor.visitVarInsn(ASTORE, 3);
        Label l13 = new Label();
        visitor.visitLabel(l13);
        visitor.visitLineNumber(33, l13);
        visitor.visitFieldInsn(GETSTATIC, "net/minecraftforge/common/MinecraftForge", "EVENT_BUS", "Lcpw/mods/fml/common/eventhandler/EventBus;");
        visitor.visitVarInsn(ALOAD, 3);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "cpw/mods/fml/common/eventhandler/EventBus", "post", "(Lcpw/mods/fml/common/eventhandler/Event;)Z", false);
        visitor.visitJumpInsn(IFNE, l9);
        Label l14 = new Label();
        visitor.visitLabel(l14);
        visitor.visitLineNumber(34, l14);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/EntityLivingBase", "isRiding", "()Z", false);
        Label l15 = new Label();
        visitor.visitJumpInsn(IFEQ, l15);
        Label l16 = new Label();
        visitor.visitLabel(l16);
        visitor.visitLineNumber(35, l16);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitInsn(ACONST_NULL);
        visitor.visitTypeInsn(CHECKCAST, "net/minecraft/entity/Entity");
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/EntityLivingBase", "mountEntity", "(Lnet/minecraft/entity/Entity;)V", false);
        visitor.visitLabel(l15);
        visitor.visitLineNumber(38, l15);
        visitor.visitFrame(F_APPEND, 2, new Object[]{"net/minecraft/entity/player/EntityPlayerMP", "net/minecraftforge/event/entity/living/EnderTeleportEvent"}, 0, null);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitVarInsn(ALOAD, 3);
        visitor.visitFieldInsn(GETFIELD, "net/minecraftforge/event/entity/living/EnderTeleportEvent", "targetX", "D");
        visitor.visitVarInsn(ALOAD, 3);
        visitor.visitFieldInsn(GETFIELD, "net/minecraftforge/event/entity/living/EnderTeleportEvent", "targetY", "D");
        visitor.visitVarInsn(ALOAD, 3);
        visitor.visitFieldInsn(GETFIELD, "net/minecraftforge/event/entity/living/EnderTeleportEvent", "targetZ", "D");
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/EntityLivingBase", "setPositionAndUpdate", "(DDD)V", false);
        Label l17 = new Label();
        visitor.visitLabel(l17);
        visitor.visitLineNumber(39, l17);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitInsn(FCONST_0);
        visitor.visitFieldInsn(PUTFIELD, "net/minecraft/entity/EntityLivingBase", "fallDistance", "F");
        Label l18 = new Label();
        visitor.visitLabel(l18);
        visitor.visitLineNumber(40, l18);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "getThrower", "()Lnet/minecraft/entity/EntityLivingBase;", false);
        visitor.visitFieldInsn(GETSTATIC, "net/minecraft/util/DamageSource", "fall", "Lnet/minecraft/util/DamageSource;");
        visitor.visitLdcInsn(damageAmount);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/EntityLivingBase", "attackEntityFrom", "(Lnet/minecraft/util/DamageSource;F)Z", false);
        visitor.visitInsn(POP);
        visitor.visitLabel(l9);
        visitor.visitLineNumber(45, l9);
        visitor.visitFrame(F_CHOP, 2, null, 0, null);
        visitor.visitVarInsn(ALOAD, 0);
        visitor.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/item/EntityEnderPearl", "setDead", "()V", false);
        visitor.visitLabel(l7);
        visitor.visitLineNumber(47, l7);
        visitor.visitFrame(F_SAME, 0, null, 0, null);
        visitor.visitInsn(RETURN);
        Label l19 = new Label();
        visitor.visitLabel(l19);
        visitor.visitLocalVariable("i", "I", null, l3, l4, 2);
        visitor.visitLocalVariable("event", "Lnet/minecraftforge/event/entity/living/EnderTeleportEvent;", null, l13, l9, 3);
        visitor.visitLocalVariable("entityplayermp", "Lnet/minecraft/entity/player/EntityPlayerMP;", null, l11, l9, 2);
        visitor.visitLocalVariable("this", "Lnet/minecraft/entity/item/EntityEnderPearl;", null, l0, l19, 0);
        visitor.visitLocalVariable("p_70184_1_", "Lnet/minecraft/util/MovingObjectPosition;", null, l0, l19, 1);
        visitor.visitMaxs(14, 4);
        visitor.visitEnd();

        classNode.visitEnd();

        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);
        classNode.accept(writer);
        return writer.toByteArray();
    }

    public static byte[] transformSlotCrafting(byte[] classBytes) {
        ClassNode classNode = new ClassNode();
        ClassReader classReader = new ClassReader(classBytes);
        classReader.accept(classNode, 0);

        for (MethodNode methodNode : Lists.newArrayList(classNode.methods)) {
            if (methodNode.name.equals("canTakeStack") && methodNode.desc.equals("(Lnet/minecraft/entity/player/EntityPlayer;)Z")) {
                methodNode.name = "old_canTakeStack";
            }
        }
        MethodVisitor mv;

        mv = classNode.visitMethod(ACC_PUBLIC, "canTakeStack", "(Lnet/minecraft/entity/player/EntityPlayer;)Z", null, null);
        mv.visitCode();
        Label l0 = new Label();
        mv.visitLabel(l0);
        mv.visitLineNumber(174, l0);
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ISTORE, 2);
        Label l1 = new Label();
        mv.visitLabel(l1);
        mv.visitLineNumber(175, l1);
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ISTORE, 3);
        Label l2 = new Label();
        mv.visitLabel(l2);
        mv.visitLineNumber(176, l2);
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ISTORE, 4);
        Label l3 = new Label();
        mv.visitLabel(l3);
        mv.visitFrame(Opcodes.F_APPEND, 3, new Object[]{Opcodes.INTEGER, Opcodes.INTEGER, Opcodes.INTEGER}, 0, null);
        mv.visitVarInsn(ILOAD, 4);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/inventory/SlotCrafting", "craftMatrix", "Lnet/minecraft/inventory/IInventory;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/inventory/IInventory", "getSizeInventory", "()I", true);
        Label l4 = new Label();
        mv.visitJumpInsn(IF_ICMPGE, l4);
        Label l5 = new Label();
        mv.visitLabel(l5);
        mv.visitLineNumber(177, l5);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/inventory/SlotCrafting", "craftMatrix", "Lnet/minecraft/inventory/IInventory;");
        mv.visitVarInsn(ILOAD, 4);
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/inventory/IInventory", "getStackInSlot", "(I)Lnet/minecraft/item/ItemStack;", true);
        Label l6 = new Label();
        mv.visitJumpInsn(IFNONNULL, l6);
        Label l7 = new Label();
        mv.visitJumpInsn(GOTO, l7);
        mv.visitLabel(l6);
        mv.visitLineNumber(178, l6);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ILOAD, 2);
        mv.visitJumpInsn(IFNE, l7);
        Label l8 = new Label();
        mv.visitLabel(l8);
        mv.visitLineNumber(180, l8);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/inventory/SlotCrafting", "craftMatrix", "Lnet/minecraft/inventory/IInventory;");
        mv.visitVarInsn(ILOAD, 4);
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/inventory/IInventory", "getStackInSlot", "(I)Lnet/minecraft/item/ItemStack;", true);
        mv.visitTypeInsn(NEW, "net/minecraft/item/ItemStack");
        mv.visitInsn(DUP);
        mv.visitFieldInsn(GETSTATIC, "net/minecraft/init/Items", "glass_bottle", "Lnet/minecraft/item/Item;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/item/ItemStack", "<init>", "(Lnet/minecraft/item/Item;)V", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "isItemEqual", "(Lnet/minecraft/item/ItemStack;)Z", false);
        Label l9 = new Label();
        mv.visitJumpInsn(IFEQ, l9);
        Label l10 = new Label();
        mv.visitLabel(l10);
        mv.visitLineNumber(181, l10);
        mv.visitVarInsn(ILOAD, 2);
        Label l11 = new Label();
        mv.visitJumpInsn(IFEQ, l11);
        Label l12 = new Label();
        mv.visitLabel(l12);
        mv.visitLineNumber(182, l12);
        mv.visitInsn(ICONST_1);
        mv.visitVarInsn(ISTORE, 3);
        mv.visitJumpInsn(GOTO, l7);
        mv.visitLabel(l11);
        mv.visitLineNumber(184, l11);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitInsn(ICONST_1);
        mv.visitVarInsn(ISTORE, 2);
        mv.visitJumpInsn(GOTO, l7);
        mv.visitLabel(l9);
        mv.visitLineNumber(186, l9);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitInsn(ICONST_1);
        mv.visitVarInsn(ISTORE, 3);
        mv.visitLabel(l7);
        mv.visitLineNumber(176, l7);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitIincInsn(4, 1);
        mv.visitJumpInsn(GOTO, l3);
        mv.visitLabel(l4);
        mv.visitLineNumber(190, l4);
        mv.visitFrame(Opcodes.F_CHOP, 1, null, 0, null);
        mv.visitVarInsn(ILOAD, 2);
        Label l13 = new Label();
        mv.visitJumpInsn(IFNE, l13);
        mv.visitVarInsn(ILOAD, 3);
        mv.visitJumpInsn(IFNE, l13);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(IRETURN);
        mv.visitLabel(l13);
        mv.visitLineNumber(191, l13);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ILOAD, 3);
        Label l14 = new Label();
        mv.visitJumpInsn(IFEQ, l14);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(IRETURN);
        mv.visitLabel(l14);
        mv.visitLineNumber(192, l14);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/EntityPlayer", "capabilities", "Lnet/minecraft/entity/player/PlayerCapabilities;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/PlayerCapabilities", "isCreativeMode", "Z");
        Label l15 = new Label();
        mv.visitJumpInsn(IFEQ, l15);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(IRETURN);
        mv.visitLabel(l15);
        mv.visitLineNumber(194, l15);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/EntityPlayer", "experienceLevel", "I");
        mv.visitInsn(ICONST_1);
        Label l16 = new Label();
        mv.visitJumpInsn(IF_ICMPGE, l16);
        Label l17 = new Label();
        mv.visitLabel(l17);
        mv.visitLineNumber(195, l17);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/EntityPlayer", "worldObj", "Lnet/minecraft/world/World;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/world/World", "isRemote", "Z");
        Label l18 = new Label();
        mv.visitJumpInsn(IFNE, l18);
        Label l19 = new Label();
        mv.visitLabel(l19);
        mv.visitLineNumber(196, l19);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitTypeInsn(NEW, "net/minecraft/util/ChatComponentText");
        mv.visitInsn(DUP);
        mv.visitLdcInsn("You need at least 1 level of XP to craft this");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/ChatComponentText", "<init>", "(Ljava/lang/String;)V", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/entity/player/EntityPlayer", "addChatMessage", "(Lnet/minecraft/util/IChatComponent;)V", false);
        mv.visitLabel(l18);
        mv.visitLineNumber(197, l18);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(IRETURN);
        mv.visitLabel(l16);
        mv.visitLineNumber(199, l16);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitInsn(DUP);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/entity/player/EntityPlayer", "experienceLevel", "I");
        mv.visitInsn(ICONST_1);
        mv.visitInsn(ISUB);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/entity/player/EntityPlayer", "experienceLevel", "I");
        Label l20 = new Label();
        mv.visitLabel(l20);
        mv.visitLineNumber(200, l20);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(IRETURN);
        Label l21 = new Label();
        mv.visitLabel(l21);
        mv.visitLocalVariable("i", "I", null, l3, l4, 4);
        mv.visitLocalVariable("this", "Lnet/minecraft/inventory/SlotCrafting;", null, l0, l21, 0);
        mv.visitLocalVariable("thePlayer", "Lnet/minecraft/entity/player/EntityPlayer;", null, l0, l21, 1);
        mv.visitLocalVariable("found", "Z", null, l1, l21, 2);
        mv.visitLocalVariable("incorrect", "Z", null, l2, l21, 3);
        mv.visitMaxs(4, 5);
        mv.visitEnd();
        classNode.visitEnd();

        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);
        classNode.accept(writer);
        return writer.toByteArray();
    }
}
